---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - /mnt/storage/config/jellyfin:/config
      - /mnt/storage/media:/media
    ports:
      - 3005:8096
    restart: unless-stopped
