keys:
  - &desk age1est4jdeu803qv6jng7vrj9x92l3xs0mr6qwv6fpt0p7tdd26xd6s84k2pq
  - &digiboksi age1dlh099k5q7uafl7esvrxtewjmmcw2vedmymfw3l8euckxxrqe9wqnhcus3
  - &server age1w785k56chrrsc29jgkjzyvxfj3lx5sx56cm5fg6ldvychdga9umspddsfg
  - &vps age1ep20tc9awnthysnluf2gf8ydr3egt26yutw527qn3ld00eugg9wqaedx0c
  - &t440p age196cqwq7cfr20zhlxwdnjrtlnn4w3ay5q52wxec5pyk2ksvq3s9ms0qjzyr
  - &framework age1xaxgua4xzu7p9545hwnzpal8rlpza95wjyz2d4at8jajsx38w4tsp87z5d
creation_rules:
  - path_regex: sops/digiboksi/[^/]+$
    key_groups:
      - age:
          - *desk
          - *framework
          - *digiboksi
  - path_regex: hosts/uwu/secrets/[^/]+$
    key_groups:
      - age:
          - *desk
          - *framework
          - *server
  - path_regex: hosts/vps/secrets/[^/]+$
    key_groups:
      - age:
          - *desk
  - path_regex: certs/[^/]+$
    key_groups:
      - age:
          - *desk
          - *framework
          - *server
  - path_regex: sops/desk/[^/]+$
    key_groups:
      - age:
          - *desk
