display:
    new: ENC[AES256_GCM,data:diaJsw==,iv:cH/pCJrDdS4a1HA9nmwqT9af3VG514sKenGtiDQxusU=,tag:b0Em1KmQfZ3qnModejfh0Q==,type:bool]
    error: ENC[AES256_GCM,data:pcSWZA==,iv:Wc73llSMAQYqGCAewHO1aNO1o1w3pX7BWv5BkaIwVP8=,tag:73Sbnsskef/nlqjeUDUTAw==,type:bool]
    unchanged: ENC[AES256_GCM,data:rZSOkJE=,iv:teK5lp7umzHGXS3CshqOu/EtXtTlO7jgpVRlALSfK78=,tag:BVhxiQ9jyNfBnegonDITiQ==,type:bool]
    empty-diff: ENC[AES256_GCM,data:jWVXXQ==,iv:3j6+ihkcOFDg5Xk9CZBD2OxmX8yYiM5Hm3G1+NY1Xlk=,tag:Sv5hlUGOodnsaXpbyGOzdg==,type:bool]
report:
    matrix:
        homeserver: ENC[AES256_GCM,data:7kb9VjYhJx0KUWY41+5INbUcQ1A7,iv:UeCqg/pptKLAFzg/8vLO2jrxYvsM0oDKLyuQ9idKMsg=,tag:mI50BPKUkCp/S7/yTyYxyQ==,type:str]
        access_token: ENC[AES256_GCM,data:QD1iyxVTQ4f6ZjN5jXvWOkrZzGXBaoH2wnUQV3XmJxY=,iv:HoVmn8j66MERWL3r06WjQIEzUdAR2TGP13vBbaxc6GU=,tag:oXQB7cDiXDOaPU6daTa9rw==,type:str]
        room_id: ENC[AES256_GCM,data:AN7Z3NqgCGE3PyyuJLqj25esifwHrVdz4hSQ1cXy7vM8w/JoErOpa1LlH3s=,iv:s8/LZDKAajICFktD0Ai18wBdWC2HT/nQjwU2/XeBA5k=,tag:IafkInbotNhn+siDHRVZLw==,type:str]
        enabled: ENC[AES256_GCM,data:T2Yq3g==,iv:qQwRf1j28NxUve+XyR4XIHkez2fhoQOEYN3P1q7/w6Y=,tag:HtYEnYwmNCPK/lVp60ph2Q==,type:bool]
    markdown:
        enabled: ENC[AES256_GCM,data:mScpgw==,iv:bDQRH7HDhuaMzCos+BqsGyK5RKAMPxGxjVt0ImkJhA8=,tag:ENS1J6X3epfSpOzn6Mr3Sg==,type:bool]
        minimal: ENC[AES256_GCM,data:SkOmhD0=,iv:jF4NI5AM5+0fPxLlJnUWk9wj+OLCROCkxBOYckfjgqE=,tag:bHFLMjN6NtbGUHUl/zuvpw==,type:bool]
        details: ENC[AES256_GCM,data:0uJY8A==,iv:gfKeuvDBe7+1RK4q1emHzIpv3SjYHX+YZ1akAOzWzMo=,tag:YUzNDud5v0SXlkJUzEy4Cg==,type:bool]
        footer: ENC[AES256_GCM,data:NtaZYFI=,iv:fwrkoyiqKmm35wL60sBHQxu/ah/8DGiqDkt+fjX6Itw=,tag:dbHzplDhA2h5m5QVepxiww==,type:bool]
    discord:
        webhook_url: ENC[AES256_GCM,data:45A4aYhA3W9QmnqH75QJAi03i6/gZK4kd3Plo0FRDBusAVhlhLTDdvRjpAfmBEgbdFPLTKR7K8oGf5lGc64DJBNG0cH9LXXVpj4eIIOHJyOavdA+UhghL4gHzu90U4QXi0NIXJjCEWO5sHoXPMDYCaebTZyL2Xz6hA==,iv:aFtuJYsLMXBM8DrK+Ubz2xxKJV3VbPyu1grlJk3UCQ0=,tag:ftL/7ydCYamYxnIX9Hog3A==,type:str]
        enabled: ENC[AES256_GCM,data:a69Ld9Y=,iv:Dudzdgcj9AJCq+VXiGXTlng9CUVyEDhQyk8pMa3TLCk=,tag:w9f8cETbkxlNI+j1K/y4Aw==,type:bool]
        embed: ENC[AES256_GCM,data:kVXw0A==,iv:XYH48J+9fc09pgeTtybYwMdqAjWl25L44PQcqUH1nBA=,tag:M61cNt792dpdlWo+r4mO1w==,type:bool]
        colored: ENC[AES256_GCM,data:u/U42g==,iv:mxP668aowskeCTOTssGTukyMz471qpUhixgOQ3dpCus=,tag:0uordDF1gDXuddiuHOhRUw==,type:bool]
        subject: ENC[AES256_GCM,data:qQ6Xor6mplhRY4pMdK0qnzko3awdie4=,iv:ytVY2xEei5c8vKf0ut9vSrRcr8j8ZhhSQ8DwebO/rNE=,tag:9gJKzKCPJ2Vaw/obu+Bt0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGc4M3lGaHAr
            Mk0vT1ZhZzRYb2YxajZ0S0hjV0VEZkdhc3ZuZ2lvM2pDZm5LK1RqSnE5RW9OZVZU
            Y1J0MmJRMEx4L3RERWtjemlTQVVKTmhlRWNIZEJ2UE4xMzRMUjV4eThoUm1kTlZu
            TzJnL0NOZk9vbXhxT0graUxsSS9QaGZWeDE5WXJqa3RUMXpsOWtFLy9WNUNZK1lQ
            Y1hNZE9tNERUMG5XRDZGZHhEbkxLSUFKbWNhbnlIcWFjSFZiVmw3U1lmUHdGeE1s
            emhvd0diQ3ZodWozMzlyWnZXZ29kWEpjVVNsL1JubXZtTlhFbStOMkdDckdqSUdI
            a1ZrVnlYeGtYc0pGQ0hkRnpUaFNCMnIxalFlWUJUZGdzYTBieEtNQlJsdGk2NVhn
            R0x6RTcxaHJ3V2doVHJ6SkNzVGFKVWVJRldvczRMYWM3STh3cmFwYjNKRnJGQkpJ
            Y2t2eklsVTlzczN4UEhEaHZMZ254K1FRak9uY3orMmd6azRHSWxZT0JGMXZmQmg4
            VEo0N1RlSzZuYUd1L3hsVFR3U0JkSjBEd2dKR3RLNjNQVFBlaGZSVk50b3JHQklj
            Z1IzY3ArbjNQTm9CYkp4YndXay9RMmdqTG5tUWtRU2wzcy9Oc2UzUmNTYWlNYXdS
            UlZnY25Oc21Yb09mZ3F5OFU2bkJ6NWRXQmNjaHVLOFlXTWJOMW1tTzFEMjhqU1Ar
            RjR3aUdkb2xDWllyZExTQ2JvOEFkVVFFUUdrNGo2ZzhKQmR2MDlkWXliSGlqU1NX
            QmFOdVFHQm1LR0UzRUxJYzU2NkdZVjduY1pKVExPRm1wZHdtc1VwZHY2cUdhODFG
            NEtGRFE5cEdpV2xnMnI3M2hiTWxiQWxqaG1HN3BOTG1oc3dObVFlaGZzUEd0Y1FX
            OHdEYzU1ekdBMFVEVTVxdlZHZzRlWk9DenZhSUR2QVVHdXVGZkVoUUNTZ0hLUXho
            LzFJd0hSejZSYm1TbWFBMkUwYk11aGExRVJJUlJrRHFHWmFQdzFTZjdFV0Q2bE9j
            NjlEdmtxZDNzcnQxNElpZFNHbWVIRStOK0t4Nkc1SGVSVUJlbnYrMWJ1Ukw2OTB0
            UEp5WnZwc1N1RDRUWEVzYmdtNFlkbW5kRVpjbUdpeWh0eE9IUXp1eE11K3dpZ1JP
            MjJuZHBTWmRaMnZ2MExXV2RCTERaSnFyTmdMUzFSRExIc2NFQUpjOE1JbXhGdTVF
            cFdramlhWEJISWVXN3NUcFU1OFM5eFdwTW81YUtBb3Urbys1SUFZQk5vMitySnVO
            c2FoVW1Ia2tGZlNBKzE3ckpTRjVOUVo5a0lIWTY0K3FRbjBwWmJGMmpCL2w2bE12
            MDk0RlpsUCtuWnFabVZWckpMajAxK2VpbndqMXJ2NXE3Z21VUnlzTmNEZXg3Z2Y2
            R2lHdFlFZndNSmZlZlJ4emVibXlDSm9UOERxbXlRUkxyUWFMSnFqV2VRdHRjSTFF
            Y1pMUW1FY3kwSVBkd1R6KzlIdFBvcDRBUmduajRwajVIeFZ1SHBTcjJlTENoM3d5
            YjJiMUR3OWlpaUhVSkt3WlZnenU4K1l5UDRJVkVRRjBxUGVkSmNzZkVjdGEyNDdW
            MFo3OFRkb002OTBtRElwTmpHRDRBTDlCdkhoQ2dKQi9sWkwzYlV3bWlPNDVOMUk0
            MnR1RngwVDd5QU5zK29rSk9WQmdpWlR6SlJlbDNmdjc4U2tHVWRqK2VCZDl2Y0I0
            Znh6cnJWQnBpamh6NDNoa3hVY3pmdjd1SlJYN2FPa29hbzl3SndZK3NOaUtVT1ZO
            L2EwdE9ubjdWQU0rL0pPSkxFMXk1SVZrelo4VVBheEV3UHNZYkw3MjhvUjNraWZq
            RkxDS1N0UkJTL2RxUmpSeWlEdEd3Y2QzVWFLUXpnZWpSTnJCYTZPTUJCZTVFVUd2
            eHQvcHgwS2xwenY5UUVNVndkaHFPcDhOY0ZSeHJlK0ljUGhNZ01DT2J0ZTNGdwo5
            V1VYYmdPSFBzQURuanNDUXZtTXVZZ2YrWDFRMld4bFFUbmR2NExnSzlRCi0tLSBx
            Y09aNmlzb2NjUlV6YkYxT3g3aGJWSjI5ZC9PeTJ3RWRDRkt1SkR5Qy84CuBsfdrb
            6lPWrCPRwEcUlhb5WOJ86IgWoygiLvxycikcyRLKC//sRBn6PorvfrCwt9pL1P01
            /l/ALbbAtBpNYNQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1znqtnw6s4xc7k07q6xedcfgxxs5hhlhuypya89577s00ka4xyvuccylsppdccn7wxy37ws4my2vcy48feqalkfhv2qwwtgcym4ysfqshepw703uf39tte97rd39cmudxpd4ujajfuryxq64yyl683gm90kzmgean6gr4vk9vnmyf0cgqgx07vtf53jkljpqcta26g75rnhj04fw45n9rwwnsn3fgdkm2s7dddvu6mfm8hdmqtuj8h43zhhpvk0un42tuzl99msf2598s36zupjfc5egd25kyfzecxmnz2rgckm2ys4ych7yj87rn0x2gqkhk3gg84wsj05ng6mkz6umxfcdqkku5uunzd65cgszp73mxpe3j2sd8hys0p4a2krmmstd803q3yegjqykmhpvelay8lmph0w9530rhrj55zdr77xng8dqhqcv0jgzcw9qzhk3y7q5gnjs3jvkg4rq8p3czqvte9mnn2swuj0tqeyh253yy867z5l95k3xjxtt9xln9qw64tfw88lyvkl6xe7yxdwpasc9yscafx97qnw33dqfs4zew2mya0ugqjedpg9e48k2kvam9wzr38ztfus3k78fekyxx50jgltqk22e0hd92f4zghxqcg0uganqh88qflmq5748n0ths93u05kk0hxy7ksjce5m9x3etjqxnzmprvdt6vcdk2tae223a8j33qy2fe4kt8n35h7pzwh9gv7u7asyn0yn33hy2zq33pd2qcfswn3jzlevysmw24nlcgfm6d2576gpvr3ujm2q2d9zt0325yglrcwfzqgyufxjn633mh7f5pplhf9nygkrt4pw8lugmjw8s5m95z64gwvtdt3m8uge6swnd9du0w3kfexkfggvfycwn97ayc80v83v9azcw3zpr7tdfsytywvhfdsgz8s9kkgzn956tt9lfjgv24rzc554ehach2tzfreuhwpva9jjzy8qhk6vz2qr5chhl3pxwxf04cymahcsfjt630we89x9fj5rkxvwg5neq04dnvh6mfjntysds97s7d99258kvwq98cafdr25yn6tac8mkzt4hphucrfkugyrvvxp4txg9grmzyk7a0nekcaaykkzqqfce4jsyh3c58yqk6fa9ue724ea992xgk0hg4396ugp5642ve77xytqzkk65dx6d50qmlgfe38k9pkdhe3pdfrwk75dusj59gea98t9zflv45hacrsysptpg6t3mgz0mx8kh8nj98y5f5lplucc93t7p8yeay9f76zsr43rpkz26ufg5tq5sz6eft2sfy2nkyetf5cs5g98cv6phd22j7gnfsdje79vmervx55lvy30dmrzs226qy59jxu55z79pay4a8yt3s8m85da6w25c4xkrevzuzfc4202cuak20720dn257dx3gujkvfxge47e8q6krjjqcwdjm73qxwu30fnfvjpmfzezlqdz9grwn2eg8yh3p9arpqyv6v88l4v674924pn8nu8nsmk5ux0ap2u9utnul49c97srtf3s0xlr6usjuygk2rms0aul8jsyy5y92h98c3qe3795c8dkyxcdcymtp9e2dct638wet6utce2nh3jjycs4hlztwegzkkhnrtjvjp39hgss5qrmtc22trdxn9emmxpysz4zrsw97xgz2qxljqg2gj47ref6cq3mcqp5ysfd48583fkq8eqh8rth7avf94sw33492r9au4us7egz3826yj4jq2gdwfp5x94rk0ukwqngvld3wuw95lq2v7yqa4cp7de5c5rqs26my3qlk5vysl7ylnlzdktavqpg02uw0rdev6nx5hh7gm0c32ynyfapx5hewvvgnrdgp6u4rzzv28jh7fzq6dlk46qn50933ftg7nl3stl6es8h3yx0cl32mmu2375e93aj9gu8695c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHBQNEJ6dnoy
            SEF5a1ZqTWpDZHRNZGFGRis3OUgxOUpwa1hNaXRNcVNNTFhwL2o1TkJickhwYkpY
            aGFFK3RUVFE0MXBYaWUzbXcwK3B6UDV3Uy9ndkNyMmZYSjBGM2NWbGFVU2pCZXVS
            MUYvaEtNVHk2V1A0L091Y1I2YjZFRWw0UWZhUVdlY0Y2eDlaeG92NGpYRGF3SGw3
            TG5OZjRZb1ZnajNHWUZtakJFZXRHNENCbktueC9BcWhvS2tPNGc1WVJMWHppYnFn
            Umswd3R4Mkpkc1FhbldmWFY5WHVwaWxkcUxQS2hmTjJLcjdpL0lpQU9MbFl4WENV
            WlJTbGZPcVcvVWt6NUVITlRpc1JlUTFsQ0FrbVpMVm5JWWJuRFlLYTlvUktIU1hq
            d2MrK2V3c2x5cGMrNVJOY2ZuSExBRnN4SGRxZWZ0RjM3MWdzb05CVVZlZTRHL3Iz
            ZVFMelZ2d3IrNEtvK05qSUluSlZRZlRLVlVjS3JJMUVaUG0vN3BTa242S0dvTlVy
            ZW1mdlBXcEZOSVVHYkplZ2xsL1o0Ujg3b0JwMnh3Y1ZHcTdtS3JWK3pmWjdURkpi
            QlFMUXAwQVpwUCtZYXU4OTkrZ0d0TDduZ3B3NnhHd2twWitPaXNBQzB1cnpJRGtJ
            ZzNPUkQ3YjVQL1NpcjcxRDVuLzZkSEV2WW8xVTBOL055VmlqTlkxd2kyRUFrOHFS
            M2ZjMUVkVHhUa1VPZHFQeFlrYWNHRStFMFdta2RJN0R4d0NkSzF1c1d4MVNESkJK
            alZ6OGJHVjRsckdNMm00S1B2SGx6dm1lalBCbE4yQkFQZDlMYXZ1N0JLZHhpLzZr
            UGZlbVFOaFdjeUFwQjkvaCt5YW5Jcit5QTVheGJqRGVuQUNaUkhWOTl0eW01UGpm
            ODZxN3FUenBBRzdGd2VBRHZNQ08rUDBTY1BybjdtckFHNnBQQVdDOUZUTjdZWW5z
            L3FLNE96K0syVTlJWStESW9YN1QxazVrS0tDNzcxR014NFBVL3VWS1JvQlVBMkly
            OG1ja0g4dWsrTjRxemd5OCt1TytMTXBVSklONExGQ0phZ3phS0Jva2RSTzVQSWoy
            ZUlWOHkrVThtdjJHN0NXcjB6NXY4NUdjR01BeHUzTy9hOEJ4bWNCYVBpVzBkQU9m
            OE80eGl2aTNwS1J1elZrSmNpQjZXTmRqbEN0eEgvVUFlNStmWWhEendySHVITDlC
            bzRVMXFRQWxmak5GbEhSQzYxdzREdmlTMU1rc3R6YmE0eW84UEVFV25lNmkrUFVD
            RjFDMjM3WWlPS0pNb3dlRG5lMDRrT1AyaFAwbEVaTVpFVFluUWxQeDhJT1doZVpF
            djgyeE5Za0k2OThickM4ZllxY2ZwQjFOY2hqdkxYMFIzZWxRNmIzVk8vRWd3S0x0
            VEZTZndwV2wvRUZHRWdEako2T1o2a01wVDlYb0hiY0JPNzhlWFNYUlk1WjliQmFK
            QlNxQ3BvSTdiL2tJS21qVVBUcnljMTMyOXBUa0ZVVjJYRW9tYjBFRDVPd2NlU3FJ
            QU41NDRQaGFwVXB1SmQ2WlBlM1NYWFhybDgyTWdmdUdkS0c1aXByb2xIVFd2Ullj
            ZWhHYnNyVVpiRzJjdEtQSUk4dC9jTGFUTTM5WkwvNHFsdWlWdHNqUW1hRWRMdndo
            UGpWNlV1ci94MThXRmxISU1xTjBnNHYxNUk3aFhEeDJqTWwxOXNCZzZmWlFRYU96
            SW5LdGpPTDgyYmwyMUovL3JIaE9FUUxlbDhsZk5HSTNkNWhDV0VKaWlaUEYrbjJU
            ckovaEtmUGFESHBUMEZzY3VqeDZ3Nm5SRnN3QUgySWhXTEhwSHhQeGZuc2dINnBN
            Y0E0b3RjMGcyQzFhUktDbnhhbFVDSnVPSE1OWmk2dFdoY2lrZnJJZ0ZtNXZNcGkx
            Z1cyR09aME1jWXNPeUxXK3QzUG9YZ2gzZ3dYRFFHa0piL04vWnR6M25ZeG1jQQpC
            cXVzSjRCU1BWWW9pdzE1ODB3cmZYOG55eFdtYVlTazJzSGlaeWZVdkR3Ci0tLSBk
            bGxjZE9qcUtjZWt1dmpabFRudUkrN3p6bVNIaEpMWG5BZVNjcFZZK0V3ChvV6xaH
            f67dSeLsqPnQ72A/vQfDYN5xKRQSEZRFobGQQTDpDn9a8bniwyH6t/jXbDIwiRkh
            SMOhZItXP8kokzc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq127ngq4q68t3gw8q2cvjqjyap8cqm2f3y4mmh3r0hwe4k7ssztnvhth3k4063v45v6wcnxpt84d2zrkmrq2q6zyjgetxmuka00z2jegwrv7sxv32f9we094pwy79ejksgxzmhnnxd4zlzrqkths49nz23cnya30nt57zv5km3fa5mfatxk6u642wg5wdqfa6mm3qx65j9yxkxd0sn8pvjp2a38gt2fcysnk8q8deaqv8xzaawlyqvysnfpg8sz35zytq8t7jaljcjt53en2ydydc9ej253svx5ujn6qmmerwrfyae8z8cp2u2azajpsh4xn9es59yjz0xla6tdqzgjhmgxy2z89wckpyfm9zpx8dsdphj27cqhz7cynr80u3u7fmfkeyfk430rt0dmdxhcjrdta4gjkfcspuakq4umqgf937p0vpthrtsrsutz5mnqjxdxynsenq5ex94cwev3rg6xzcl0sv6sscvp6etk9nnkmukk9zesmqnl25sq4fe5734sw35ws8daatqd4qh2v7e0v494ty7zkrmc3400rgrh29xr7q75psa5rrcxjq6kluy5szz4033t9nzw39ayju0q6f3lumkxtxyxdvvhxf3w3j6s2dxlservl0pgg9k9zypa6maz9ee93xyef36nyc7r9ew72p2jrsukupgtgrurfwk9fu4v0y00c46utrr20tpnqxqc4z93e3qjszftd8rs79nff3003z6r6rwqsfuufdx833qjdc053ew3frmddf5j266v77tcsgsswnx0f30k4tgg474e6sl5hekuvwxhdu7vwdrszvuy872q7mmmpkss7r4nn69mpj2w4c7ws9edxf3vasv2gvp88ucz3dc54tuw5mzm4dgmdsewgqyfpye8j9k99dn939m2qu9pnv9pl3680ldnvc7kfkzu0j9v92ur9jrssltssxdmy2klpdz304hyul2vukh6nrhe9tv4lf65d9ewkg80xup9ptx2vzr5f6unrxz804qcpt96ek07jzr0g4637neg8u6xktdxesk62rd82jsksgz4r6vnfu4xv0zcyatjyru77mu5ee9cac7xpwpcccllvcyd7puk75jqqcnqj77nem72lde3vyh3k4y4nqw9q2r6g6ccvgpk3tf4lh5dthm3v4efk4skyetzun4r43hzzu3qekygcdhn9szngx44mvmw9eyaznzlu5n8hytjg2vsul83wudp8gqfsnz6rsjpx7c5lca50zcpga5zdpn766gmz8496fqctzvj7dmdjpqjjstg8fux52w0yt6pww0us6lnvy4v90sk4efzqmzrjtp5uf5w74qafhmgstvhfgv4vyaxxveu4ekd9tywqsyzhzm0dvs6j94ghsvwygmpwyawc80nyttksakpepuhm48eqp09wugvlx7u0q7zhdv0s7fwazl290qrqnx5er59df3z02kvl76r2sn5qav7x94xqf9gwf3s7cpgyw4f094xfwpfayky63p8nwpr9wecakc036famn9m3ljng6082xy4su50wuztzwxd5d8k6h2pt6lxp64lg4702f2p6uq0s0wgy3hd3ndu34nsuur8nms8p5627rrxzdz7wzmlhd9gkjyjqqdvhksvnpuuqcxta6yjrlx56uznqz4ef85q2gepgznyvapqsxzcr3g2vmhm4ulf6gxlyuf9t8v59p5pvmfpz3pddckrfdk0muu0w3dxtq3ufjx2lv3yzc3vqjt8x0lkpud2g5emp7xj98yjld6yzuxvz3jjq359xwql5rjr60xrns8dstxuecwjnuc3l7hqevpwhrnxg6fch2zuukk53hptrm4vmupzlrrqajt84jpnh2fcyqjqrvlt8dym46352ka6sn08ts2fxjfxce4cgrfxu65z3q4uym57e7qkeuulu93w54m2qz0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHB1RVhUajlp
            UkwxbVhVd3N3a1g5YjNPMDg2OEh4S2dSaHFEZ3pxMXFwcmRxQk9VOWRmbWJRSGNL
            Z01pekRPSk82QmxoL0lxcUgzVGFRVzZJSW8yWHVhT2E3ZFNqemR6ZTlCcjc3TVZj
            WDF5b2RzVG0zamxaRVlFMkNwYmUxM1ZWT2Q3ZTlUaVVNNk9wRkFFUkRUNEtscDNE
            Y2IwRkNvekxoZ1ZOTFJXOU5mSXlncmswTHZGSHFqbjZwNDFNbDk4eFJTRE5OK2ha
            VmkySXV3UkNaZDBOd2pvUkNHNGhQOU9FazVnRUljQU1nbGtWWis4VzYyNnBIT2lM
            Z05jT1NwbExCM2lvdHV3Rmh6MVhSYUJXY0Y2aENFaVBXdlNHMzdwU3o4QUYyR2dp
            TnZqZXQ1MFVrQ29zQ0lmbWlBOWJHQ2ZFdWFSc3grdTI3bkdkMlJIaTlOYmhuaHJQ
            M0FoTmlnempFQmpwbnV2eGRrSTBsUnp6c0VudnpFSE1PZlVqQmVhbDJtU2JGbzBT
            ZmRJUER5N2pKNm9BUDRsNjBWeUplbDI1L1JPeE5vNWJ2QUVhZFNtU0JBcHFzM0w3
            R2xkV2FjeHN5MTBRWjdVZlhnTmU3eFJpMDI1cnMzcWp0KytOdWNlaFdvaW5ienU0
            VVhJamp6eEpyUjNDUDE3azZXOEgzRmpoaEpRdUhzeVlWZ1Nra2VMZExNaTBQQkNl
            Z0NOY2JqbTllZ3J4UkVCU0ZidFdaSlFlWUpXMWh6bUlLbkNCejJIV0psb2ppdUhi
            U2FxOVZGZ3Z2ZC9CVWpmalVuZ1dmVEV4R2JWS3RWVWNvd0dueWZaMUg5aGdBK0lD
            VlBaNnJwRlo1d2FCR0krL2R5V1pvNVc0ekJabzk2RVkySGlvelFnL3RpUmF4R3dD
            TFd4RHZvaWRMVCtTOXBPTlRGdmZ3N0dNZGhTYlFJanVaeUxscGNna0R4QmVqR1Rl
            bWxrZ2NoNUlUeTAzalJPamVxL1pjd1BHeTVNOWtjOUdFSVMyWjk0NzF5TjdIYk9M
            b1lYNXEyVU5nWnNNRFYwNFQ4elpKNlhzdDJFbUprT2dJS244cGZjb0NOZHdTT2dZ
            MDVManZzcmRkbEtNUHRlVE5SS3RyZnJpVFRnOWZQRDE1WTZRYXVTY3NlLzFWaVFn
            bDB5a2t3ZVp1M082YmhwNHFoSlhXTjRyeXFHck1xMDNteG93TThzcjNYR2xNZkto
            OEFwVmdZZG5DTzNNcUJmTFNsTDFHdW1SKzNHK1lSblZwYmxucXBPWWdpT0pWT1NO
            TTRqaXRBV0hxQ1JHOE4wUHR0ME9pejh2TlFNemQzWVZ0bUJQZUVMaUQwMFFQT1d2
            a25UZEtJNzZEb2x3cVM4NDJPdGswaGY3N1Y0c3pvYlZsclFRVUpZVE5KM3djK25j
            YzFONkNIY05ZVlNkd1FlSDR0Znord1ltcGcyZG5CY1c1d2VKYk5rcnNtWCtpS3Zn
            LzlXRUpvMHRvcnVoMHc2K2hJVkRDcFRkSHJ1dmI5WDNveU0zb0xuMkxGMkhuQUYy
            OTNLbkQ2TVFLTnI2QXg4RW1pL1RzNU9GcHF4a093NngzVnd3dkc2RkdZSTI5M0lk
            b0ZERnYza0dGaE9XQnhLTEhhR25PNXh6SDJtdWQ2enZtQisxMDA0TkE1eHh4UTJz
            M0RkODlVRE12YSsrNmRwZ0FORDl1UkVHWmlXQXMxWUdGdm94WXNldC8zZHp1SzNY
            VE5USUc4RXVXK3lIR2RSQUNBOUZBY01MR1hucElkV1kzS2wwN0REMGRsYkVZZ3c2
            R090dWs3OVF3MU4zd3dyVE56U3RicFJEeUZNZVBOOFBrNm92QXMyR2RRU3cvVnor
            eSthMmFYWFRxRldjY3d6M0E3cmRTbGQyR0FUZCtRY0RaMmF5K2lyYmxLUGxWaE1z
            U1RRNlI4VGdMRFdPV2NFcExPZ2ZMVnErdkxvcnRWOG5OTXp5RC80cWxrSmRUdwpG
            NmRhNjEwNzQrVmdiYkdrTmE2QzJWVkMyWU4yYjk5L3JKci9meXBHU1g4Ci0tLSAx
            dUdBa1pSSnQ1ZlRmZ25wcWVUWG53dVgzbDlUZTNPbkpkSlVyZWU1ZWVVCrD+zNzu
            f1lYKE5dBX4TlvBHQai05gp+7bMRxOxtaFuyVY/PYKbKTn5Tc142P4PtXyw/8IBD
            XuVaTw62JISdG9M=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1ntfqk8egd0denzq95l85rxulta98zzjskkpdvvtf7vg0a2z0ug2qe033hsth3g9n79x32hppfxg4sreexany3paescnxt542qud80lrq5vmxtnuy2gdqcpplynp38gepx9z3wy02t92y3as5293uczvu46kw0fs0nqfuxj4chgnmwapysh542l3fpvxjjf3enn3f0f223m4pdrmngny24jmx5rd3vjpggkf3hy0qgwm7vpy3ateq8wcswzslq4f4uh8hrj5cjdv6z6k832xzyjh2cea6lzn7yunclyu4g3shnpgf7p9pc7ye78kxy8ymp9nmd25wdpepl5y35pqng903e0ywv5atx9rynjggk56kwpgqw9xhp38kqskv6v46d33xvhxgq503gspfnsdzg4f8uhyq4jd8vwac3vscj5ve97nlhqgxzp2twy0w38jssc2ddmze90q2w9wmywuus7vvtgnf6rrevgf5xkuffpn6gvrt73079sd6gwuq25ysyadmt2amvq2g89ts5x9pl2seq4nedwmr5vck8fn5r0jhpg4rvjpx580u7saes92z7nz3syv6zvguqj5ywv6k4epx3cyxpjc8y0dawxpjz5saqk79jaemy64ggpqcgw5ce98qtwsnqwcy9huf94zqpqat0wazlaj73aa46v8svy8qczp75fht7p7fw9nh4yv3gl2qzh0ltxcttvx2dknqtz8js7as2zsyvw24zkms40yht29xgaazvkw2y2nq97tz3g72ztu9j0n9erpcj3y7affvkev82fum8rthrdzlx4lfp7mscvgz3tszs6lmcmm3uynxpyw2jasx44fqqc9xqcr82u450wmq8mj39gejpsugfy6rvwyk0wunn0s5k7w840mu0fcntg6ff6ehyaas8zr507qsyktj78qlsjfh7kwxcw0sgpwwj8pzudppd3rhemm9yq8pv4kxxmy9p368zu572uj69fzhy2h6c6f77skzvdw2sk5khzcrdm3jzrtv3xtkak9v4mgnlux6wckm03ths320exwgh34h4nvq426mcy6fj4fy7j6m9tysq2vzyyf6wqs4yx3m2s5herdcdmc9hwe6fyhgfw6wwjqjp6u5vvsejajkevwclp4zrd4yrlgjudj2p4czqpdnx7uequegjh2pqmx5jscm3ze0qz23umymkwfyuvwky0lf2e43ydunv9jsadnthu9etk3z2xcwdxknawn3vte6f6w4y0t9wp4mxk33dxvtz35kh2wtnngs2wu9nsz995z2zdscm2ahs43rzdssqs3l9eulkn3uth9t2sv33jjdlrxva6m4zl4z4d02fkm9cc88gkr4d95596d6xnpp5dqqy82n2swskwd20yjzkwmjnp6x5086gp7hrgynr8mrq2ey8lnxp0ajmgyxtpzagre62nqnhgsr5nr2mw3tv5g8w2vhjpk9g2wcgd5aj32z45ca2akfexmhpmz2cy825jux36ekhum2u8zvx5tccu39q2lv6ap4s24m0tykettaxvs4tqsxn92eawm3glruwarqhrzfx307skq9fvsu5g2scxp4c44y82h0gu98rp4kmzlx3g6snf7w5dxjck4pdp3c5uqgv20rhrw9920t009hds22njmqnal3vlpcqvv24a46yh5rk5g69qg5pvgtg9uqfsacq4th5nxkrt0ugyne2d4s0v7rdzt54dytc3hu8nug2zgdzdxx6trqt43y0ppqfvdu0f8sy63mhyjua7g4wtgksrjwv7rkgwwgggdflugc0ldakl4avkt6s9mul06efv7y8lq6qdzsyennttppq7p5l98sjr3de4u5cel0j4tgd2mcclaeyrqqlkjy585arq7zx59slczqe4yyaltafwzn6wt0mfpuh32x0y53xc6cwa93wf0s9yqaclvr
    lastmodified: "2026-07-23T09:10:51Z"
    mac: ENC[AES256_GCM,data:H6ENyBwNlnn3Mh50l98KKJ7ZGrXp724mjN+xIIx0o+eh88Irljqw9ibkZeR8jHFaWbHZDq1EKn4L3QAhfRSBG7HOahw+FWOTo2MhOLpsNfNQ4cZ5IUf9TxW8NfRo2Ufi1AAMSxM3PzM488E4nOwvs6gJhKZgQDGWdpDBdUSagZs=,iv:OGKUJywaPp7GVrwg5B17AbpleOJazxuYkY0oKqxiLiA=,tag:aPWlFfMHOGs6lWs+ZDATZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
