{
	"data": "ENC[AES256_GCM,data:gLNxjxyYuaXZyvORvfHsGldWkHMYBBZzhIHywDhAGhVIsikAwOIYhUVsIohMWtdJHbl322rNE3w6/0Rkv3Zb4RWBr6xYVJdKfuQ5RhkvuzHhvrzY8b7uPjcwv/VkPgNMCGnv8o4Ae89iAOVAi04kmfuIxtLkf8qZ8UIdgmJf1bJzI0fK8hXxyRhIt/sl4rC5WT7+PZr69LK+qd4EWtmMu6CLZ/mpOoFjxjHDTbPvmdUB7YTozI/mMPJRKO5r0vEeRTu6EYgSai7X5WXiVRjHoso5erXGCgQw/qi4mvxUBi7xl2e45vgw+NraJrosI2fbIxGip+CQthkBPQ0/+30nt6Ob1n1zqqROYtfyLi3zLuQyj3PDk8bsVYqd+j+xL6eX/qH6v8kp03WIThLuplND7FuGEIXT2i/rsrrL7ho9fb0HOCAbQLt3E0WfI175vM5zchdq+kNXoWePuau4COoRr+lhNf1KgFvIqnbSr9r8FyAsGmVbjv8HsrV4Gjvjw2yrYX126lzW8O4aEsgeyXINS2RWiswMGXceC0ggnTNSlIUud/wvR/BXUPOtgIIYOHpxAQbk/MrKGQwzDAtLDiCwmtXGssTUzen+41ZKU4nzDojFVOZ/ModVnG+T2SOv+PPAcVoIU0olrMeiuS6nh/Imtlhm0teB8/hAJSUYf15ALDZeyMHhyRPEGZElECLXlRG3bkR2jOPkVKgSGbaySpRbJwivxri0lIqjT+7YGXBkMPCs5CwShw==,iv:O31gG94UQge9v5+AqCCn5V7NBZ9QI9p1z/nwrZF59pQ=,tag:owYYPk9jVN9rMo9A/bwiKQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1est4jdeu803qv6jng7vrj9x92l3xs0mr6qwv6fpt0p7tdd26xd6s84k2pq",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQXB4b0lueHRWeXovckRt\nSUNibkFFWW9XdUxGa2RHUVhqRzNlNVlRYUdzCjZGajc5WkhDcXIyV2g5MVNVZ0Y3\nbHg5Ujh1TzFBMUV3MGtyZlNHRy9nSEUKLS0tIE1DUk1meVRaOVpyWU92SG9jRDV3\nNG5qQUlud0JweGVLeW14M05Hd0d6VWcK20WG8+qZiE1yG2KZXP3EC+cCtJ7jxUf0\n5IzfRAtRSGb5/0c0fFIpfaSgQF3RFUwD9K3ailhiaIfVUQBwqLYAAQ==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1xaxgua4xzu7p9545hwnzpal8rlpza95wjyz2d4at8jajsx38w4tsp87z5d",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUU0rNXdBd2ZwN2RFZUZD\nOURVdHFTYWNFYUwvanBzVUQyc1FBUnJMUm5FCjdjdGp5clBKenB3eTJCMDdPU3ZC\nQytBMkE2dEVWN3plcFZtVCtCL08rYzgKLS0tIE9NR1ZzUFZuR3NtUThUT0k1cnU4\nYXowV3U0VENOdnJCeWtBSmhnKzliQmcKo4xArV9nYpiO0P8gBSLjG2Gy1gbl7tiC\nst3FQVFPPG+vElpQymyfajI0QgEzrQgWG4VJexauRFR4GHpVBhWmIw==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1w785k56chrrsc29jgkjzyvxfj3lx5sx56cm5fg6ldvychdga9umspddsfg",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMWhobUIweVd4QTZTKzRC\nVHhhZGtGcmtUVm5URkU5dzhJVEZrdkdFclJzClJCTzJEaXFOVURVeGZXWGlQY3J5\neUdqRG84UTVKcCtSci9iVDhZbVF0L2MKLS0tIHBYUUVwVmZaZ0hVaEZNQmJ5QVYw\nTTVXM01ydEFFSnZxSzNvdVpXZGFBRTgKg31CKbSOxRE4oYaoHUzENCx4ueJMpwjM\nkS2ucA7C+cVbtphtc+T4r+SgizkXGEAyAnSzit/iDcIToD4vfuRQAA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-01-01T19:02:17Z",
		"mac": "ENC[AES256_GCM,data:Ij+ea0Jg9YwODmUuw3VJkzpHehBYbR7FPgQVnVAh2VHqvQkn7AlC+Jll0jIIw2+XJ94cFeKfMt3Z9+DQVXnGW6fW/ImBxY+ot0PxRTpQ5L5AXJu93gXHazF7KX8NXv+WvmHHW+E3bLtsfcJFGRdFmrbWGLOQ09cSM6MEhIYA69k=,iv:3OKRFizBWbIno6m/JxRjU6T+kNNMw7efPmMrNttOyIM=,tag:fVQ0K6XHN6r5YwtN5XFZ3A==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.9.2"
	}
}
