{
	"data": "ENC[AES256_GCM,data:gLNxjxyYuaXZyvORvfHsGldWkHMYBBZzhIHywDhAGhVIsikAwOIYhUVsIohMWtdJHbl322rNE3w6/0Rkv3Zb4RWBr6xYVJdKfuQ5RhkvuzHhvrzY8b7uPjcwv/VkPgNMCGnv8o4Ae89iAOVAi04kmfuIxtLkf8qZ8UIdgmJf1bJzI0fK8hXxyRhIt/sl4rC5WT7+PZr69LK+qd4EWtmMu6CLZ/mpOoFjxjHDTbPvmdUB7YTozI/mMPJRKO5r0vEeRTu6EYgSai7X5WXiVRjHoso5erXGCgQw/qi4mvxUBi7xl2e45vgw+NraJrosI2fbIxGip+CQthkBPQ0/+30nt6Ob1n1zqqROYtfyLi3zLuQyj3PDk8bsVYqd+j+xL6eX/qH6v8kp03WIThLuplND7FuGEIXT2i/rsrrL7ho9fb0HOCAbQLt3E0WfI175vM5zchdq+kNXoWePuau4COoRr+lhNf1KgFvIqnbSr9r8FyAsGmVbjv8HsrV4Gjvjw2yrYX126lzW8O4aEsgeyXINS2RWiswMGXceC0ggnTNSlIUud/wvR/BXUPOtgIIYOHpxAQbk/MrKGQwzDAtLDiCwmtXGssTUzen+41ZKU4nzDojFVOZ/ModVnG+T2SOv+PPAcVoIU0olrMeiuS6nh/Imtlhm0teB8/hAJSUYf15ALDZeyMHhyRPEGZElECLXlRG3bkR2jOPkVKgSGbaySpRbJwivxri0lIqjT+7YGXBkMPCs5CwShw==,iv:O31gG94UQge9v5+AqCCn5V7NBZ9QI9p1z/nwrZF59pQ=,tag:owYYPk9jVN9rMo9A/bwiKQ==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1est4jdeu803qv6jng7vrj9x92l3xs0mr6qwv6fpt0p7tdd26xd6s84k2pq",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvejVlcDdCaFlNWlNUYVZ3\ndzcyNnQwa1h1RFNCN01EcldoNlBQSVp2NTA4Cnp3MngrMW02VE92YUwrRk40Q2l2\nVWl1RUxxWkJWeFdvS0NVWUJGYkRkMjAKLS0tIHp4NWhhdlhXenQ3aEN4YytoaWt4\nT1VLNmp5NnhQVjNHV2lnQzVMQ1lCSEEKQG6SUACEF+6sjM660y9pMAyX2TPG8a2e\nOmKxKI5VKnTw5QLrubo+Qy7ujHdRl5A6w23ZyhqO3dIm4/fE2rf8PQ==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1dlh099k5q7uafl7esvrxtewjmmcw2vedmymfw3l8euckxxrqe9wqnhcus3",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV0daQTNKYktWUVZNNVM1\naU8vOHFhS1BiK2g5TDZTVEpQZ2lMd25Meld3CmpJY2J3a3dCdk13UnAvN1BUeUlm\nTVZlSkwxZzZJb0JEOFRFNkRIUW5FTm8KLS0tIDJaMytwV25SVXVNK1oveitpUEJi\nQ2lTU2F4RGVRMGNqbGRTUlRkNUNlQlEKtQJ1TFLb++eYcnM5SOPXQ9zEWhfNUjY4\nRIO2vWWxmVYX4cxwlQ2KE2YC2/lO47t6oxOXiDbDjgRMYG65z+KuYw==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1w785k56chrrsc29jgkjzyvxfj3lx5sx56cm5fg6ldvychdga9umspddsfg",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZVp6SEd1aENWcEhMS0Ir\nU00vVDhtT1BvVjRXTWtuY1pmdXNjQ2JQaVVNCkRMakZqVmRsc1RlVU0rMFZHeUVq\nVXJjUkZ3aEE0R1RGTjZWSDRqYk1nNEUKLS0tIGZOaW1nS1d1dk1JdGhvb2tMek9h\nSzdTd1g4UWhHZmViRUVwOUY2RFNUdWMKDAiUpePcHMNHcLvCgK3smpHvE1qi373B\ngrDH0Lp0YN/Jsw3gwP7Lt0GExH7/LlzNfag+8Z+XXSV3t4d3HQ/qVw==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age196cqwq7cfr20zhlxwdnjrtlnn4w3ay5q52wxec5pyk2ksvq3s9ms0qjzyr",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaEhSWkxUTmZLVnQwMnBT\nZFN0MUVhVWpPSlB5ZVhMbE9JdyttTkVUd21vCno0K1JVRTJUcHg5cXFHenVUcWFQ\nNnB6eHRDWUQxdUtxUUZjV24wK3lvSlEKLS0tIFlsYnB4QVdtcmR2ZzRxY2drTUhH\nT2d6MFI4ZUNlT2hIOENQV3pRVXFNL3MKyXeAhg4ONGBhnr+w+t4j6YJioRHdBPQ1\nFFYju973XjmGX2sSQ+8qATb8jMGDsCRV7T9V/yOEpXhhrsZzonWViQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-01-01T19:02:17Z",
		"mac": "ENC[AES256_GCM,data:Ij+ea0Jg9YwODmUuw3VJkzpHehBYbR7FPgQVnVAh2VHqvQkn7AlC+Jll0jIIw2+XJ94cFeKfMt3Z9+DQVXnGW6fW/ImBxY+ot0PxRTpQ5L5AXJu93gXHazF7KX8NXv+WvmHHW+E3bLtsfcJFGRdFmrbWGLOQ09cSM6MEhIYA69k=,iv:3OKRFizBWbIno6m/JxRjU6T+kNNMw7efPmMrNttOyIM=,tag:fVQ0K6XHN6r5YwtN5XFZ3A==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.9.2"
	}
}