jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: wimpysworld/nothing-but-nix@v6
      with:
        hatchet-protocol: rampage
        nix-permission-edict: true
        witness-carnage: true
    - name: Nix Installer
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        install_options: --no-daemon
    - name: Cachix
      uses: cachix/cachix-action@v16
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: meowos
    - name: Build desktop
      run: nix build --accept-flake-config .#nixosConfigurations.desktop.config.system.build.toplevel
    - name: Build digiboksi
      run: nix build --accept-flake-config .#nixosConfigurations.digiboksi.config.system.build.toplevel
    - name: Build framework
      run: nix build --accept-flake-config .#nixosConfigurations.framework.config.system.build.toplevel
    - name: Build iso
      run: nix build --accept-flake-config .#nixosConfigurations.iso.config.system.build.toplevel
    - name: Build t440p
      run: nix build --accept-flake-config .#nixosConfigurations.t440p.config.system.build.toplevel
    - name: Build uwu
      run: nix build --accept-flake-config .#nixosConfigurations.uwu.config.system.build.toplevel
    - name: Build vps
      run: nix build --accept-flake-config .#nixosConfigurations.vps.config.system.build.toplevel
    - name: Build x220
      run: nix build --accept-flake-config .#nixosConfigurations.x220.config.system.build.toplevel
'on':
  workflow_dispatch: {}
