name: Build Hosts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  # schedule:
  #   - cron: "0 02 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - uses: actions/checkout@v4
      - name: Lix Installer
        run: curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm --extra-conf "trusted-users = root runner"
      - uses: cachix/cachix-action@v16
        with:
          name: meowos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build t440p
        run: nix build --accept-flake-config .#nixosConfigurations.t440p.config.system.build.toplevel
      - name: Build server
        run: nix build --accept-flake-config .#nixosConfigurations.uwu.config.system.build.toplevel
