name: build-hosts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    paths-ignore:
      - ".github/**"
  workflow_dispatch:
jobs:
  build-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@v4
      - name: Lix Installer
        run: curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm --extra-conf "trusted-users = root runner"
      - uses: cachix/cachix-action@v16
        with:
          name: meowos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build desktop
        run: nix build --accept-flake-config .#nixosConfigurations.desktop.config.system.build.toplevel
