jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: wimpysworld/nothing-but-nix@v6
      with:
        hatchet-protocol: rampage
        witness-carnage: true
    - env:
        NIX_INSTALLER_EXTRA_CONF: |-
          trusted-users = root runner
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      name: Lix Installer
      run: curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix
        | sh -s -- install --no-confirm
    - name: Cachix
      uses: cachix/cachix-action@v16
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: meowos
    - name: Build desktop
      run: nix build --accept-flake-config .#nixosConfigurations.desktop.config.system.build.toplevel
    - name: Build digiboksi
      run: nix build --accept-flake-config .#nixosConfigurations.digiboksi.config.system.build.toplevel
    - name: Build framework
      run: nix build --accept-flake-config .#nixosConfigurations.framework.config.system.build.toplevel
    - name: Build iso
      run: nix build --accept-flake-config .#nixosConfigurations.iso.config.system.build.toplevel
    - name: Build miniso
      run: nix build --accept-flake-config .#nixosConfigurations.miniso.config.system.build.toplevel
    - name: Build t440p
      run: nix build --accept-flake-config .#nixosConfigurations.t440p.config.system.build.toplevel
    - name: Build uwu
      run: nix build --accept-flake-config .#nixosConfigurations.uwu.config.system.build.toplevel
    - name: Build vps
      run: nix build --accept-flake-config .#nixosConfigurations.vps.config.system.build.toplevel
    - name: Build x220
      run: nix build --accept-flake-config .#nixosConfigurations.x220.config.system.build.toplevel
'on':
  workflow_dispatch: {}
