jobs:
  update-vps:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy update to vps
      run: |-
        echo "${{ secrets.VPS_DEPLOY_SSH_KEY }}" > ~/deploykey
        chmod 600 ~/deploykey

        mkdir -p ~/.ssh
        ssh-keyscan -H kotiboksi.xyz >> ~/.ssh/known_hosts

        ssh -t -v -o BatchMode=yes -i ~/deploykey deploy@kotiboksi.xyz
'on':
  workflow_dispatch: {}
