jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: wimpysworld/nothing-but-nix@v6
      with:
        hatchet-protocol: rampage
    - env:
        GH_TOKEN: $${{ secrets.GITHUB_TOKEN }}
      name: Lix Installer
      run: |-
        curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm --extra-conf 'trusted-users = root runner
        access-tokens = github.com=PAT:glpat-$GH_TOKEN'
    - name: Cachix
      uses: cachix/cachix-action@v16
      with:
        authToken: $${{ secrets.CACHIX_AUTH_TOKEN }}
        name: meowos
    - name: Update Flake Inputs
      run: nix flake update --accept-flake-config
    - name: Build framework
      run: nix build --accept-flake-config .#nixosConfigurations.framework.config.system.build.toplevel
    - name: Build uwu
      run: nix build --accept-flake-config .#nixosConfigurations.uwu.config.system.build.toplevel
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: main
        commit_author: Flake Bot Update <actions@github.com>
        commit_message: 'chore(deps): bump flake.lock'
        commit_user_name: Flake Bot Update
        file_pattern: flake.lock
        skip_dirty_check: false
        skip_fetch: true
name: Update flake.lock
'on':
  schedule:
  - cron: 0 03 */2 * *
  workflow_dispatch: {}
