name: Update flake.lock
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      HOSTS: t440p server
    permissions:
      contents: write
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lix Installer
        run: curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm --extra-conf "trusted-users = root runner"
      - uses: cachix/cachix-action@v16
        with:
          name: meowos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Update flake inputs
        run: nix flake update
      - name: Build hosts
        run: |
          for host in $HOSTS; do
            nix build --accept-flake-config .#nixosConfigurations.$host.config.system.build.toplevel
          done

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(deps): bump flake.lock"
          commit_user_name: Flake Bot Update
          commit_author: Flake Bot Update <actions@github.com>
          branch: main
          file_pattern: flake.lock
          skip_dirty_check: false
          skip_fetch: true
