jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: wimpysworld/nothing-but-nix@v6
      with:
        hatchet-protocol: rampage
        witness-carnage: true
    - name: Nix Installer
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Cachix
      uses: cachix/cachix-action@v16
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: meowos
    - name: Download flake.lock
      uses: actions/download-artifact@v4
      with:
        name: flake-lock
    - name: Build ${{ matrix.target }}
      run: nix build .#${{ matrix.target }} --print-build-logs
    strategy:
      matrix:
        target:
        - nixosConfigurations.vps.pkgs.meowdzbot
        - nixosConfigurations.vps.pkgs.sodexobot
        - nixosConfigurations.vps.pkgs.leptos-kotiboksi
  update:
    needs:
    - build-crates
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: wimpysworld/nothing-but-nix@v6
      with:
        hatchet-protocol: rampage
        witness-carnage: true
    - name: Nix Installer
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Cachix
      uses: cachix/cachix-action@v16
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: meowos
    - name: Download flake.lock
      uses: actions/download-artifact@v4
      with:
        name: flake-lock
    - name: Build uwu
      run: nix build --accept-flake-config .#nixosConfigurations.uwu.config.system.build.toplevel
    - name: Build vps
      run: nix build --accept-flake-config .#nixosConfigurations.vps.config.system.build.toplevel
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: main
        commit_author: Flake Bot Update <actions@github.com>
        commit_message: 'chore(deps): bump flake.lock'
        commit_user_name: Flake Bot Update
        file_pattern: flake.lock
        skip_dirty_check: false
        skip_fetch: true
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: wimpysworld/nothing-but-nix@v6
      with:
        hatchet-protocol: rampage
        witness-carnage: true
    - name: Nix Installer
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Cachix
      uses: cachix/cachix-action@v16
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: meowos
    - name: Update flake.lock
      run: nix flake update --accept-flake-config
    - name: Upload flake.lock
      uses: actions/upload-artifact@v4
      with:
        name: flake-lock
        path: flake.lock
        retention-days: 1
name: Update flake.lock
'on':
  workflow_dispatch: {}
